package model;

import lombok.Getter;

public enum Sign {

    FOOL("Głupiec", 0),
    BLINDMAN("Ślepiec", 1),
    MUTE("Niemowa", 2),
    DEAF("Głuchy", 3),
    LEPER("Trędowaty", 4),
    JAGGED("Szczerbaty", 5),
    LAME("Kulawy", 6),
    ARMLESS("Bezręki", 7),
    SOUTHERN_CROSS("Krzyż Południa", 8),
    COLT("Źrebię", 9),
    ARROW("Strzała", 10),
    CIRCLE("Cyrkiel", 11),
    SHIELD("Tarcza", 12),
    SOUTHERN_TRIANGLE("Trójkąt Południowy", 13),
    NET("Sieć", 14),
    GRAVER("Rylec", 15),
    SOUTHERN_CROWN("Korona Południowa", 16),
    CAMELEON("Kameleon", 17),
    TRIANGLE("Trójkąt", 18),
    FLY("Mucha", 19),
    FLYING_FISH("Ryba Latająca", 20),
    TABLE_MOUNTAIN("Góra Stołowa", 21),
    BEVEL("Węgielnica", 22),
    NORTHERN_CROWN("Korona Północna", 23),
    GOLDFISH("Złota Ryba", 24),
    SMALL_DOG("Mały Pies", 25),
    RAVEN("Kruk", 26),
    DOLPHIN("Delfin", 27),
    LIZARD("Jaszczurka", 28),
    PARADISE_BIRD("Ptak Rajski", 29),
    MICROSCOPE("Mikroskop", 30),
    COMPASS("Kompas", 31),
    SMALL_LION("Mały Lew", 32),
    ALTAR("Ołtarz", 33),
    PUMP("Pompa", 34),
    WATER_SNAKE("Wąż Wodny", 35),
    SOUTHERN_FISH("Ryba Południowa", 36),
    PAINTER("Malarz", 37),
    CLOCK("Zegar", 38),
    TELESCOPE("Luneta", 39),
    SMALL_BEAR("Mała Niedźwiedzica", 40),
    FOXY("Lisek", 41),
    PIGEON("Gołąb", 42),
    CUP("Puchar", 43),
    LUTR("Lutnia", 44),
    HARE("Zając", 45),
    OCTANT("Oktant", 46),
    INDIAN("Indianin", 47),
    TOUCAN("Tukan", 48),
    SEXTANT("Sekstant", 49),
    WOLF("Wilk", 50),
    CRANE("Żuraw", 51),
    PEACOOK("Paw", 52),
    BIG_DOG("Wielki Pies", 53),
    BERENICA_BRAID("Warkocz Bereniki", 54),
    FURNACE("Piec", 55),
    CAPRICORN("Koziorożec", 56),
    ARIES("Baran", 57),
    HOUND_DOGS("Psy Gończe", 58),
    FENIX("Feniks", 59),
    SCULPTOR("Rzeźbiarz", 60),
    UNICORN("Jednorożec", 61),
    KEEL("Kil", 62),
    SCORPIO("Skorpion", 63),
    SAIL("Żagiel", 64),
    CANCER("Rak", 65),
    GEMINI("Bliźnięta", 66),
    SCALES("Waga", 67),
    LYNX("Ryś", 68),
    CEFEUS("Cefeusz", 69),
    ORION("Orion", 70),
    CASJOPEJA("Kasjopeja", 71),
    PERSEUS("Perseusz", 72),
    SNAKE("Wąż", 73),
    EAGLE("Orzeł", 74),
    CARTER("Woźnica", 75),
    STERN("Rufa", 76),
    ANDROMEDA("Andromeda", 77),
    GIRAFEE("Żyrafa", 78),
    BULL("Byk", 79),
    SWAN("Łabędź", 80),
    SAGITTARIUS("Strzelec", 81),
    FISH("Ryby", 82),
    WOLUNTEER("Wolarz", 83),
    LION("Lew", 84),
    SNAKEMAN("Wężownik", 85),
    AQUARIUS("Wodnik", 86),
    CENTAUR("Centaur", 87),
    DRAGON("Smok", 88),
    PEGASUS("Pegaz", 89),
    ERYDNA("Erydan", 90),
    HERKULES("Herkules", 91),
    WHALE("Wieloryb", 92),
    BIG_BEAR("Wielka Niedźwiedzica", 93),
    VIRGIN("Panna", 94),
    HYDRA("Hydra", 95),
    DREZEN_HAND("Dłoń Drezena", 96),
    ELLANIA_HAIR("Włosy Ellani", 97),
    HARDON_FOOT("Stopa Hardona", 98),
    IGNOS_EYE("Oko Ignosa", 99);

    @Getter
    private final String namePL;
    @Getter
    private final int number;

    Sign(String namePL, int number) {
        this.namePL = namePL;
        this.number = number;
    }

    @Override
    public String toString() {
        return this.namePL + " (" + this.number + ")";
    }
}
